### ISSUE TITLE
file does not open

### ISSUE THREAD

**Issue by myrmoteras** [plazi/GoldenGATE-Imagine#37]
I have tried this scanned pdf to open with born-digital and scanned text digitzed and as pdf. Neither worked.

[newZealandJZoology.19.151-162.pdf](https://github.com/plazi/GoldenGATE-Imagine/files/10831205/newZealandJZoology.19.151-162.pdf)
[GgImagine.20230225-1316.out.zip](https://github.com/plazi/GoldenGATE-Imagine/files/10831217/GgImagine.20230225-1316.out.zip)

**Comment by gsautter** [comment]
"born-digital" doesn't work because it's scanned, and "scanned, text digitized" doesn't work because the text is present in the scans as well ... "scanned, text digitized" is only for PDFs where the text layer of the scans has been _completely replaced_ by rendered text, as in this example: 
[MONTE-1943-Tingideos_americanos_Image_OCR.resaved.pdf](https://github.com/plazi/GoldenGATE-Imagine/files/10832664/MONTE-1943-Tingideos_americanos_Image_OCR.resaved.pdf)

Likewise, "scanned, text vectorized" if  only for PDFs where the text layer of the scans has been _completely replaced_ by font backed vector graphics (DjVu compression).

For every other scanned PDF, with or without embedded OCR, simply use "PDF (scanned)" as used to before I put in these two quite exotic options to handle a few papers POA came up with ...

**Comment by gsautter** [comment]
Using "PDF (scanned)", it decodes just fine (just remove the `.zip` from the file name, had to add it because GitHub doesn't accept `.imf` files):
[newZealandJZoology.19.151-162.pdf.imf.zip](https://github.com/plazi/GoldenGATE-Imagine/files/10832708/newZealandJZoology.19.151-162.pdf.imf.zip)
